import Html from "_components/details/HtmlTag";
import "./globals.css";
import { Children } from "_types";
import type { Metadata } from "next";
import localFont from "next/font/local";

const peyda = localFont({
  src: [
    { path: "_assets/fonts/peyda/thin.ttf", weight: "100" },
    { path: "_assets/fonts/peyda/extraLight.ttf", weight: "200" },
    { path: "_assets/fonts/peyda/light.ttf", weight: "300" },
    { path: "_assets/fonts/peyda/regular.ttf", weight: "400" },
    { path: "_assets/fonts/peyda/medium.ttf", weight: "500" },
    { path: "_assets/fonts/peyda/semiBold.ttf", weight: "600" },
    { path: "_assets/fonts/peyda/bold.ttf", weight: "700" },
    { path: "_assets/fonts/peyda/extraBold.ttf", weight: "800" },
    { path: "_assets/fonts/peyda/black.ttf", weight: "900" },
  ],
  variable: "--font-peyda",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Children;
export default function RootLayout(props: Props) {
  const { children } = props;

  return (
    <Html>
      <body className={`${peyda.variable} font-sans`}>{children}</body>
    </Html>
  );
}
